var definitions = {
	'platform_id' : ['', 'Android', 'iOS'],
	'status' : ['Inactive', 'Active'],
	'location_status' : ['Inactive', 'Active'],
	'isenter' : ['', 'Enter', 'Left'],
	'fields_device' : {'id':'Id', 'device_name':'Device Name', 'platform_id':'Platform', 'username':'Owner', 'device_os_version':'OS', 'status':'Status'},
	'app_device_type': ['', 'android', 'ios', 'both'],
	'app_category_id': ['', 'Business', 'Others'],
	'app_platform': ['', 'Android', 'iOS'],
	'app_device_type': ['', 'Phone', 'Tab', 'Both'],
	'app_status': ['', 'Active', 'Inactive', 'Resigned'],
	'platform' : ['', 'Android', 'iOS', 'Both'],
	'organization_id' : ['', 'Mimos Berhad'],
	'location_status' : ['', 'Active', 'Hidden'], // Values TBC
	'alphanumeric': ['Disabled' ,'Enabled'],
	'auto_lock': ['Disabled' ,'Enabled'],
	'grace_period': ['Disabled' ,'Enabled'],
	'history': ['Disabled' ,'Enabled'],
	'max_age': ['Disabled' ,'Enabled'],
	'max_fail': ['Disabled' ,'Enabled'],
	'min_complex_char': ['Disabled' ,'Enabled'],
	'min_length': ['Disabled' ,'Enabled'],
	'simple': ['Disabled' ,'Enabled'],
	'sms_logging': ['Disabled' ,'Enabled'],
	'allow_compromised_device': ['Disabled' ,'Enabled'],
	'allow_remote_locate': ['Disabled' ,'Enabled'],
	'allow_remote_lock_factory_reset': ['Disabled' ,'Enabled'],
	'call_logging': ['Disabled' ,'Enabled'],
}
